//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        public int HotelRoomId { get; set; }
        public string HotelRoomName { get; set; }
        public int RoomSize { get; set; }
        public string RoomType { get; set; }
    
        public virtual HotelBooking HotelBooking { get; set; }
        public virtual HotelRoomType HotelRoomType { get; set; }
        public virtual HotelRoomSize HotelRoomSize { get; set; }
    }
}
