//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelTamagotchiDBEntities : DbContext
    {
        public HotelTamagotchiDBEntities()
            : base("name=HotelTamagotchiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<HotelBooking> HotelBookings { get; set; }
        public virtual DbSet<HotelRoom> HotelRooms { get; set; }
        public virtual DbSet<HotelRoomSize> HotelRoomSizes { get; set; }
        public virtual DbSet<HotelRoomType> HotelRoomTypes { get; set; }
        public virtual DbSet<PlayerUser> PlayerUsers { get; set; }
        public virtual DbSet<Tamagotchi> Tamagotchis { get; set; }
    }
}
