//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelBooking()
        {
            this.Tamagotchis = new HashSet<Tamagotchi>();
        }
    
        public int HotelRoomId { get; set; }
    
        public virtual HotelRoom HotelRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tamagotchi> Tamagotchis { get; set; }
    }
}
