//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelTamagotchi.Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tamagotchi
    {
        public int TamagotchiId { get; set; }
        public string Name { get; set; }
        public bool IsALive { get; set; }
        public int Age { get; set; }
        public int Money { get; set; }
        public int Level { get; set; }
        public int Health { get; set; }
        public int Boredom { get; set; }
        public int PlayerUserId { get; set; }
        public Nullable<int> HotelRoomId { get; set; }
    
        public virtual HotelBooking HotelBooking { get; set; }
        public virtual PlayerUser PlayerUser { get; set; }
    }
}
